version: 2
jobs:
  build:

    docker:
      - image: circleci/node:11.6.0

    branches:
      only:
        - master

    working_directory: ~/Docs

    environment:
      - GH_NAME: CommunityChain
      - GH_EMAIL: business@comc.io

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Prepare deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            chmod +x ./deploy.sh

      - run:
          name: Deploy
          command: yarn deploy
